require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/gathering_outings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GatheringOuting. As you add validations to GatheringOuting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GatheringOuting.create! valid_attributes
      get gathering_outings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      gathering_outing = GatheringOuting.create! valid_attributes
      get gathering_outing_url(gathering_outing)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_gathering_outing_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      gathering_outing = GatheringOuting.create! valid_attributes
      get edit_gathering_outing_url(gathering_outing)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GatheringOuting" do
        expect {
          post gathering_outings_url, params: { gathering_outing: valid_attributes }
        }.to change(GatheringOuting, :count).by(1)
      end

      it "redirects to the created gathering_outing" do
        post gathering_outings_url, params: { gathering_outing: valid_attributes }
        expect(response).to redirect_to(gathering_outing_url(GatheringOuting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GatheringOuting" do
        expect {
          post gathering_outings_url, params: { gathering_outing: invalid_attributes }
        }.to change(GatheringOuting, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post gathering_outings_url, params: { gathering_outing: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gathering_outing" do
        gathering_outing = GatheringOuting.create! valid_attributes
        patch gathering_outing_url(gathering_outing), params: { gathering_outing: new_attributes }
        gathering_outing.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the gathering_outing" do
        gathering_outing = GatheringOuting.create! valid_attributes
        patch gathering_outing_url(gathering_outing), params: { gathering_outing: new_attributes }
        gathering_outing.reload
        expect(response).to redirect_to(gathering_outing_url(gathering_outing))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        gathering_outing = GatheringOuting.create! valid_attributes
        patch gathering_outing_url(gathering_outing), params: { gathering_outing: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested gathering_outing" do
      gathering_outing = GatheringOuting.create! valid_attributes
      expect {
        delete gathering_outing_url(gathering_outing)
      }.to change(GatheringOuting, :count).by(-1)
    end

    it "redirects to the gathering_outings list" do
      gathering_outing = GatheringOuting.create! valid_attributes
      delete gathering_outing_url(gathering_outing)
      expect(response).to redirect_to(gathering_outings_url)
    end
  end
end
